### ISSUE TITLE
Jira bug 24/1-2

### ISSUE THREAD

**Issue by maxAtSW** [Cyberark-workato-dev/secrets-provider-for-k8s#12]
##description
Steps to reproduce:

Current Results:asdasdasd

Expected Results:asdasd

Error Messages:dadsadasd

Logs:

Other Symptoms:

Tenant ID / Pod Number:

##Found in version
11.8

##Workaround Complexity
There's a complex workaround

##Workaround Description
asdasdasdas

`
1
23
34

fsdd
fssfd

##Link to JIRA bug
https://ca-il-jira-test.il.cyber-ark.com/browse/ONYX-6478

**Comment by daphnaab** [comment]
Comment and then back to jason team

**Comment by maxAtSW** [comment]
//Author: Daphna.Abulafia@cyberark.com

Comment rom Jira and priority low
